update from production

diff --git a/shell/om-clear-code-cache b/shell/om-clear-code-cache
--- a/shell/om-clear-code-cache
+++ b/shell/om-clear-code-cache
@@ -1,13 +1,11 @@
 #!/bin/bash
 
-: '
-om-clear-code-cache
-Clear various caches to ensure code changes are picked up
-
+: '---------------------------------------------------------------------------------------------------------------
+om-clear-code-cache      # Clear various caches to ensure code changes are picked up
 - Sequence: First use safe bash commands to clear FS paths, only then use cachetool.
 - The cachetool commands will fail harmlessly except on the production server, but we need the
   other commands to succeed on all hosts.
-'
+------------------------------------------------------------------------------------------------------------------'
 
 # set -e      # Exit immediately if a command exits with a non-zero status
 set -u      # Treat unset variables as an error when substituting
@@ -16,20 +14,26 @@ set -u      # Treat unset variables as an error when substituting
 cm || die "Failed to go to the openmage directory"
 . ./shell/cron-bootstrap.sh || die "Failed to run ./shell/cron-bootstrap.sh"
 
+
 # Clear PHP opcache stored in shared memory
 rm -r /dev/shm/openmage-php-opcache/* && touch /dev/shm/openmage-php-opcache/CACHEDIR.TAG
 echo "Cleared PHP opcache in /dev/shm/openmage-php-opcache/"
 
 
 # Remove minified CSS/JS files that are over 14 days old
-cm || exit 1
-if [ -d "media/min" ]; then
-	find media/min -type f \( -name '*.js' -o -name '*.css' -o -name '*.br' \) -mtime +14 -print -exec rm -f {} \;
-	touch media/min/CACHEDIR.TAG
-	echo "Trimmed minified CSS/JS files in media/min/ (removed files older than 14 days)"
-else
-	echo "Directory media/min does not exist, skipping trimming of minified files"
-fi
+#cm || exit 1
+#if [ -d "media/min" ]; then
+#	find media/min -type f \( -name '*.js' -o -name '*.css' -o -name '*.br' \) -mtime +14 -print -exec rm -f {} \;
+#	touch media/min/CACHEDIR.TAG
+#	echo "Trimmed minified CSS/JS files in media/min/ (removed files older than 14 days)"
+#else
+#	echo "Directory media/min does not exist, skipping trimming of minified files"
+#fi
+
+
+# Clear Magento/OpenMage caches
+n98-magerun.phar cache:clean
+echo "Cleared OpenMage caches"
 
 
 # Clear APCu and Opcache via cachetool
@@ -39,10 +43,6 @@ ELASTIC_APM_ENABLED=false cachetool --config=.cachetool-cli.yaml opcache:reset
 echo "Cleared APCu and Opcache caches via cachetool"
 
 
-# Clear Magento/OpenMage caches
-n98-magerun.phar cache:clean
-echo "Cleared OpenMage caches"
-
 # Wrap up
-cm || exit 1
+cm || die "Failed to go to the openmage directory"
 . ./shell/cron-wrapup.sh
diff --git a/shell/om-compress-assets b/shell/om-compress-assets
--- a/shell/om-compress-assets
+++ b/shell/om-compress-assets
@@ -43,5 +43,18 @@ find "$DIR" -type f \( -iname "*.css" -o -iname "*.js" -o -iname "*.json" -o -in
   touch -r "${file}" "${file}.gz"
   touch -r "${file}" "${file}.zst"
 done
-
 echo "Compression complete and mtimes synchronized."
+
+# Remove minified CSS/JS files that are over 14 days old
+cm || die "Failed to go to the openmage directory"
+if [ -d "media/min" ]; then
+  find media/min -type f \( -name '*.js' -o -name '*.css' -o -name '*.br' \) -mtime +14 -print -exec rm -f {} \;
+  touch media/min/CACHEDIR.TAG
+  echo "Trimmed minified CSS/JS files in media/min/ (removed files older than 14 days)"
+else
+  echo "Directory media/min does not exist, skipping trimming of minified files"
+fi
+
+# Wrap up
+cm || die "Failed to go to the openmage directory"
+. ./shell/cron-wrapup.sh
